### ISSUE TITLE
Building pxt currently fails

### ISSUE THREAD

**Issue by JohnVidler** [JohnVidler/microbit-docker-builds#1]
Pxt builds are currently failing with the following error trace:

```
#13 222.7 Using target core with build engine none
#13 222.7   target: v /opt/pxt/pxt
#13 222.7   pxt-core: v /opt/pxt/pxt
#13 222.8 building target.json in /opt/pxt/pxt...
#13 222.9 building bundled libs/blocksprj
#13 223.8 Updating cached API info for empty
#13 223.9 target-strings.json built
#13 223.9 target.json built.
#13 223.9 [01:00:27] Finished 'targetjs' after 2.25 s
#13 223.9 [01:00:27] Starting 'reactCommon'...
#13 229.1 [01:00:32] Finished 'reactCommon' after 5.19 s
#13 229.1 [01:00:32] Starting 'reactCommonPackageJson'...
#13 229.1 [01:00:32] Finished 'reactCommonPackageJson' after 1.47 ms
#13 229.1 [01:00:32] Starting 'buildcss'...
#13 229.1 [01:00:32] Starting 'buildSVGIcons'...
#13 229.3 [webfont-generator] Using deprecated templateOptions 'baseClass'. Use 'baseSelector' instead.
#13 230.2 Generated icons.css - 28772 bytes
#13 230.2 [01:00:33] Finished 'buildSVGIcons' after 1.08 s
#13 230.3 Using target core with build engine none
#13 230.3   target: v7.5.29 /opt/pxt/pxt
#13 230.3   pxt-core: v7.5.29 /opt/pxt/pxt
#13 230.3 [run] node /opt/pxt/pxt/node_modules/less/bin/lessc theme/style.less built/web/semantic.css --include-path=node_modules/semantic-ui-less:node_modules/pxt-core/theme:theme/foo/bar:theme:node_modules/pxt-core/react-common/styles:react-common/styles:node_modules/@fortawesome:node_modules/pxt-core/node_modules/@fortawesome
#13 239.9 [run] node /opt/pxt/pxt/node_modules/less/bin/lessc theme/blockly.less built/web/blockly.css --include-path=node_modules/semantic-ui-less:node_modules/pxt-core/theme:theme/foo/bar:theme:node_modules/pxt-core/react-common/styles:react-common/styles:node_modules/@fortawesome:node_modules/pxt-core/node_modules/@fortawesome
#13 248.5 [run] node /opt/pxt/pxt/node_modules/less/bin/lessc react-common/styles/react-common-skillmap-core.less built/web/react-common-skillmap.css --include-path=node_modules/semantic-ui-less:node_modules/pxt-core/theme:theme/foo/bar:theme:node_modules/pxt-core/react-common/styles:react-common/styles:node_modules/@fortawesome:node_modules/pxt-core/node_modules/@fortawesome
#13 249.8 [run] node /opt/pxt/pxt/node_modules/less/bin/lessc react-common/styles/react-common-authcode-core.less built/web/react-common-authcode.css --include-path=node_modules/semantic-ui-less:node_modules/pxt-core/theme:theme/foo/bar:theme:node_modules/pxt-core/react-common/styles:react-common/styles:node_modules/@fortawesome:node_modules/pxt-core/node_modules/@fortawesome
#13 258.4 [01:01:01] Finished 'buildcss' after 29 s
#13 258.4 [01:01:01] Starting 'cleanSkillmap'...
#13 258.4 [01:01:01] Finished 'cleanSkillmap' after 2.2 ms
#13 258.4 [01:01:01] Starting 'buildSkillmap'...
#13 289.1 
#13 289.1 > skillsmap@0.1.0 build /opt/pxt/pxt/skillmap
#13 289.1 > react-scripts build
#13 289.1 
#13 291.2 /opt/pxt/pxt/skillmap/node_modules/react-scripts/config/webpack.config.base.js:749
#13 291.2             '!**/src/setupProxy.*',
#13 291.2                                   ^
#13 291.2 
#13 291.2 SyntaxError: Unexpected end of input
#13 291.2     at Module._compile (internal/modules/cjs/loader.js:723:23)
#13 291.2     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#13 291.2     at Module.load (internal/modules/cjs/loader.js:653:32)
#13 291.2     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
#13 291.2     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
#13 291.2     at Module.require (internal/modules/cjs/loader.js:692:17)
#13 291.2     at require (internal/modules/cjs/helpers.js:25:18)
#13 291.2     at Object.<anonymous> (/opt/pxt/pxt/skillmap/node_modules/react-scripts/config/webpack.config.js:7:23)
#13 291.2     at Module._compile (internal/modules/cjs/loader.js:778:30)
#13 291.2     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#13 291.2 npm ERR! code ELIFECYCLE
#13 291.2 npm ERR! errno 1
#13 291.2 npm ERR! skillsmap@0.1.0 build: `react-scripts build`
#13 291.2 npm ERR! Exit status 1
#13 291.2 npm ERR! 
#13 291.2 npm ERR! Failed at the skillsmap@0.1.0 build script.
#13 291.2 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#13 291.2 
#13 291.2 npm ERR! A complete log of this run can be found in:
#13 291.2 npm ERR!     /root/.npm/_logs/2022-05-22T01_01_34_305Z-debug.log
#13 291.2 [01:01:34] 'buildSkillmap' errored after 33 s
#13 291.2 [01:01:34] Error: Command failed: npm run build
#13 291.2 /opt/pxt/pxt/skillmap/node_modules/react-scripts/config/webpack.config.base.js:749
#13 291.2             '!**/src/setupProxy.*',
#13 291.2                                   ^
#13 291.2 
#13 291.2 SyntaxError: Unexpected end of input
#13 291.2     at Module._compile (internal/modules/cjs/loader.js:723:23)
#13 291.2     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#13 291.2     at Module.load (internal/modules/cjs/loader.js:653:32)
#13 291.2     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
#13 291.2     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
#13 291.2     at Module.require (internal/modules/cjs/loader.js:692:17)
#13 291.2     at require (internal/modules/cjs/helpers.js:25:18)
#13 291.2     at Object.<anonymous> (/opt/pxt/pxt/skillmap/node_modules/react-scripts/config/webpack.config.js:7:23)
#13 291.2     at Module._compile (internal/modules/cjs/loader.js:778:30)
#13 291.2     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#13 291.2 npm ERR! code ELIFECYCLE
#13 291.2 npm ERR! errno 1
#13 291.2 npm ERR! skillsmap@0.1.0 build: `react-scripts build`
#13 291.2 npm ERR! Exit status 1
#13 291.2 npm ERR! 
#13 291.2 npm ERR! Failed at the skillsmap@0.1.0 build script.
#13 291.2 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#13 291.2 
#13 291.2 npm ERR! A complete log of this run can be found in:
#13 291.2 npm ERR!     /root/.npm/_logs/2022-05-22T01_01_34_305Z-debug.log
#13 291.2 
#13 291.2     at ChildProcess.exithandler (child_process.js:294:12)
#13 291.2     at ChildProcess.emit (events.js:198:13)
#13 291.2     at ChildProcess.EventEmitter.emit (domain.js:466:23)
#13 291.2     at maybeClose (internal/child_process.js:982:16)
#13 291.2     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
#13 291.2 [01:01:34] 'default' errored after 2.23 min
#13 291.3 npm ERR! code ELIFECYCLE
#13 291.3 npm ERR! errno 1
#13 291.3 npm ERR! pxt-core@7.5.29 build: `gulp`
#13 291.3 npm ERR! Exit status 1
#13 291.3 npm ERR! 
#13 291.3 npm ERR! Failed at the pxt-core@7.5.29 build script.
#13 291.3 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#13 291.3 
#13 291.3 npm ERR! A complete log of this run can be found in:
#13 291.3 npm ERR!     /root/.npm/_logs/2022-05-22T01_01_34_386Z-debug.log
------
executor failed running [/bin/sh -c cd /opt/pxt &&     git clone -b v7.5.29 https://github.com/microsoft/pxt pxt &&     cd /opt/pxt/pxt &&     npm install &&     npm run build]: exit code: 1
```

**Comment by JohnVidler** [comment]
Or alternatively, the following via actions: https://github.com/JohnVidler/microbit-docker-builds/runs/6540569046?check_suite_focus=true#step:3:7531
